sudo: required

language: python

python:
  - '3.6'

install:
  - 'pip install pipenv'

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml
before_install:
  - sudo apt-get install make
script:
  - docker-compose up -d
  - docker-compose ps
  - make fast-pylint
  - make test

after_script