language: python
services: docker
sudo: required
python:
  - '3.6'
branches:
  - master
before_install:
  - sudo apt-get install make
install:
  - 'pip install pipenv'
env:
  - COMPOSE_FILE=docker-compose.yml
script:
  - ln -Tfs docker-compose.ci.yml docker-compose.yml
  - docker-compose up -d
  - docker ps -al
  - pipenv install --dev
  # - pipenv run python manage.py db init
  # - pipenv run python manage.py db migrate
  - pipenv run python manage.py db upgrade
  - make fast-pylint
  - make test